// <auto-generated />
namespace ShoolOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _071817 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_071817));
        
        string IMigrationMetadata.Id
        {
            get { return "201707180552474_071817"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
