USE [DERMSL_Test]
GO

/****** Object:  Table [dbo].[MemberCodes]    Script Date: 7/13/2017 9:50:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MemberCodes](
	[MemberCodesID] [int] IDENTITY(1,1) NOT NULL,
	[MemberCode] [varchar](6) NOT NULL,
	[MEMBERSignupDataID] [int] NULL,
 CONSTRAINT [PK_TestMemberCode] PRIMARY KEY CLUSTERED 
(
	[MemberCodesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ckMemberCode] UNIQUE NONCLUSTERED 
(
	[MemberCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


